# ResNetCRNN_varylength Training Configuration
model:
  name: "ResNetCRNN_varylength"
  cnn_encoder: "resnet50"
  rnn_decoder: "lstm"
  hidden_size: 512
  num_layers: 2
  dropout: 0.5
  variable_length: true
  max_frames: 32

training:
  epochs: 50
  batch_size: 16  # 可变长度需要较小的batch size
  learning_rate: 0.001
  weight_decay: 1e-4
  optimizer: "adam"
  scheduler: "step"
  step_size: 20
  gamma: 0.1
  
data:
  dataset: "UCF101"
  data_path: "/data2/lpq/video-classification/jpegs_256_processed/"
  action_name_path: "configs/data/UCF101actions.pkl"
  min_frames: 8
  max_frames: 32
  frame_size: 224
  num_classes: 101
  train_split: 0.8
  val_split: 0.2
  
augmentation:
  horizontal_flip: true
  random_crop: true
  color_jitter: true
  normalize:
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]

checkpoint:
  save_dir: "results/ResNetCRNN_varylength/result"
  save_freq: 5
  resume: null  # 默认值：None表示创建新目录开始训练，数字表示从指定epoch继续训练
  pretrained: true

logging:
  log_dir: "results/ResNetCRNN_varylength/result/outputs/logs"
  tensorboard: true
  wandb: false
