# SwinTransformer-RNN with Density Proxy Generation Module Configuration
# 使用密度代理生成模块的SwinTransformer-RNN配置

# 数据配置
data:
  data_path: "jpegs_256"  # 视频数据路径
  action_name_path: "data/UCF101actions.pkl"  # 动作名称文件路径
  num_classes: 101  # 类别数量
  frame_size: 224  # 帧尺寸
  num_frames: 16  # 帧数
  val_split: 0.2  # 验证集比例
  train_split: 0.8  # 训练集比例

# 训练配置
training:
  epochs: 50  # 训练轮数
  batch_size: 32  # 批处理大小
  learning_rate: 0.001  # 学习率
  optimizer: "adam"  # 优化器
  weight_decay: 1e-4  # 权重衰减
  scheduler: "step"  # 学习率调度器
  step_size: 20  # 学习率衰减步长
  gamma: 0.1  # 学习率衰减因子

# 模型配置
model:
  # SwinTransformer编码器配置
  CNN_fc_hidden1: 1024
  CNN_fc_hidden2: 768
  CNN_embed_dim: 512
  dropout: 0.0
  use_pretrained: true
  
  # RNN解码器配置
  RNN_hidden_layers: 3
  RNN_hidden_nodes: 512
  RNN_FC_dim: 256

# 检查点配置
checkpoint:
  save_dir: "results/swintransformer_RNN_density/result"  # 模型保存目录
  pretrained: true  # 是否使用预训练权重
  save_freq: 10  # 保存频率
  resume: null  # 恢复训练的epoch（null表示从头开始）

# 日志配置
logging:
  log_dir: "results/swintransformer_RNN_density/result/outputs/logs"  # 日志目录

# 密度代理生成模块配置
density_proxy:
  use_density_proxy: true  # 是否使用密度代理特征
  density_config:
    input_size: 224  # 输入图像尺寸
    density_map_size: 32  # 密度图尺寸
    gaussian_kernel_size: 5  # 高斯核大小
    gaussian_sigma: 1.0  # 高斯标准差
    contrast_alpha: 1.5  # 对比度增强参数
    contrast_beta: 30  # 对比度增强偏移

# 数据增强配置
augmentation:
  horizontal_flip: true  # 水平翻转
  random_crop: false  # 随机裁剪
  color_jitter: true  # 颜色抖动
  normalize:
    mean: [0.485, 0.456, 0.406]  # 归一化均值
    std: [0.229, 0.224, 0.225]  # 归一化标准差
