# SwinTransformer-RNN with Both Density and Velocity Features
# 同时使用密度和速度特征的SwinTransformer-RNN训练配置

# 数据配置
data:
  data_path: "/path/to/your/dataset"
  action_name_path: "/path/to/action_names.txt"
  num_classes: 101
  frame_size: 224

# 训练配置
training:
  epochs: 50
  batch_size: 32
  learning_rate: 0.001

# 检查点配置
checkpoint:
  save_dir: "/path/to/save/models"
  pretrained: true

# 日志配置
logging:
  log_dir: "/path/to/logs"

# 密度代理生成模块配置
density_proxy:
  use_density_proxy: true  # 启用密度特征
  density_config:
    input_size: 224
    density_map_size: 32
    gaussian_kernel_size: 5
    gaussian_sigma: 1.0
    contrast_alpha: 1.5
    contrast_beta: 30

# 速度代理生成模块配置
velocity_proxy:
  use_velocity_proxy: true  # 启用速度特征
  velocity_config:
    input_size: 224
    velocity_map_size: 32
    flow_method: "farneback"
    flow_params:
      pyr_scale: 0.5
      levels: 3
      winsize: 15
      iterations: 3
      poly_n: 5
      poly_sigma: 1.2
      flags: 0

# 模型架构配置
model:
  CNN_fc_hidden1: 1024
  CNN_fc_hidden2: 768
  CNN_embed_dim: 512
  dropout_p: 0.0
  use_pretrained: true
  RNN_hidden_layers: 3
  RNN_hidden_nodes: 512
  RNN_FC_dim: 256
  k: 101
  log_interval: 10
  begin_frame: 1
  end_frame: 28
  skip_frame: 1
